//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisServiceClients.BarsNomenclature {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.bars-open.ru/med/lis/", ConfigurationName="BarsNomenclature.LisBarsSendNomenclature")]
    public interface LisBarsSendNomenclature {
        
        // CODEGEN: Generating message contract since the operation sendNomenclature is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="sendNomenclature", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LisServiceClients.BarsNomenclature.sendNomenclatureResponse1 sendNomenclature(LisServiceClients.BarsNomenclature.sendNomenclatureRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bars-open.ru/med/lis/")]
    public partial class Nomenclature : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string code_lpuField;
        
        private string code_taField;
        
        private string name_taField;
        
        private int is_groupField;
        
        private string parent_taField;
        
        private int actionField;
        
        private int is_compField;
        
        private int is_calcField;
        
        private int is_microField;
        
        private System.Nullable<int> is_sensField;
        
        private Test[] testField;
        
        private MC[] mcField;
        
        private Bio[] bioField;
        
        private Locus[] locusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string code_lpu {
            get {
                return this.code_lpuField;
            }
            set {
                this.code_lpuField = value;
                this.RaisePropertyChanged("code_lpu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string code_ta {
            get {
                return this.code_taField;
            }
            set {
                this.code_taField = value;
                this.RaisePropertyChanged("code_ta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string name_ta {
            get {
                return this.name_taField;
            }
            set {
                this.name_taField = value;
                this.RaisePropertyChanged("name_ta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int is_group {
            get {
                return this.is_groupField;
            }
            set {
                this.is_groupField = value;
                this.RaisePropertyChanged("is_group");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string parent_ta {
            get {
                return this.parent_taField;
            }
            set {
                this.parent_taField = value;
                this.RaisePropertyChanged("parent_ta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int action {
            get {
                return this.actionField;
            }
            set {
                this.actionField = value;
                this.RaisePropertyChanged("action");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int is_comp {
            get {
                return this.is_compField;
            }
            set {
                this.is_compField = value;
                this.RaisePropertyChanged("is_comp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int is_calc {
            get {
                return this.is_calcField;
            }
            set {
                this.is_calcField = value;
                this.RaisePropertyChanged("is_calc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int is_micro {
            get {
                return this.is_microField;
            }
            set {
                this.is_microField = value;
                this.RaisePropertyChanged("is_micro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=9)]
        public System.Nullable<int> is_sens {
            get {
                return this.is_sensField;
            }
            set {
                this.is_sensField = value;
                this.RaisePropertyChanged("is_sens");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("test", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public Test[] test {
            get {
                return this.testField;
            }
            set {
                this.testField = value;
                this.RaisePropertyChanged("test");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mc", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public MC[] mc {
            get {
                return this.mcField;
            }
            set {
                this.mcField = value;
                this.RaisePropertyChanged("mc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("bio", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public Bio[] bio {
            get {
                return this.bioField;
            }
            set {
                this.bioField = value;
                this.RaisePropertyChanged("bio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("locus", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public Locus[] locus {
            get {
                return this.locusField;
            }
            set {
                this.locusField = value;
                this.RaisePropertyChanged("locus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bars-open.ru/med/lis/")]
    public partial class Test : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string research_codeField;
        
        private string research_nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string research_code {
            get {
                return this.research_codeField;
            }
            set {
                this.research_codeField = value;
                this.RaisePropertyChanged("research_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string research_name {
            get {
                return this.research_nameField;
            }
            set {
                this.research_nameField = value;
                this.RaisePropertyChanged("research_name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bars-open.ru/med/lis/")]
    public partial class Locus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string loc_codeField;
        
        private string loc_nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string loc_code {
            get {
                return this.loc_codeField;
            }
            set {
                this.loc_codeField = value;
                this.RaisePropertyChanged("loc_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string loc_name {
            get {
                return this.loc_nameField;
            }
            set {
                this.loc_nameField = value;
                this.RaisePropertyChanged("loc_name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bars-open.ru/med/lis/")]
    public partial class Bio : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bio_codeField;
        
        private string bio_nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string bio_code {
            get {
                return this.bio_codeField;
            }
            set {
                this.bio_codeField = value;
                this.RaisePropertyChanged("bio_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string bio_name {
            get {
                return this.bio_nameField;
            }
            set {
                this.bio_nameField = value;
                this.RaisePropertyChanged("bio_name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.bars-open.ru/med/lis/")]
    public partial class MC : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mc_codeField;
        
        private string mc_nameField;
        
        private int mc_typeField;
        
        private int mc_sizeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string mc_code {
            get {
                return this.mc_codeField;
            }
            set {
                this.mc_codeField = value;
                this.RaisePropertyChanged("mc_code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string mc_name {
            get {
                return this.mc_nameField;
            }
            set {
                this.mc_nameField = value;
                this.RaisePropertyChanged("mc_name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int mc_type {
            get {
                return this.mc_typeField;
            }
            set {
                this.mc_typeField = value;
                this.RaisePropertyChanged("mc_type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int mc_size {
            get {
                return this.mc_sizeField;
            }
            set {
                this.mc_sizeField = value;
                this.RaisePropertyChanged("mc_size");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.bars-open.ru/med/lis/")]
    public partial class sendNomenclatureResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int resultField;
        
        private sendNomenclatureResponseError[] errorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("error", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public sendNomenclatureResponseError[] error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("error");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.bars-open.ru/med/lis/")]
    public partial class sendNomenclatureResponseError : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string code_lpuField;
        
        private string code_taField;
        
        private string error_msgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string code_lpu {
            get {
                return this.code_lpuField;
            }
            set {
                this.code_lpuField = value;
                this.RaisePropertyChanged("code_lpu");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string code_ta {
            get {
                return this.code_taField;
            }
            set {
                this.code_taField = value;
                this.RaisePropertyChanged("code_ta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string error_msg {
            get {
                return this.error_msgField;
            }
            set {
                this.error_msgField = value;
                this.RaisePropertyChanged("error_msg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendNomenclatureRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendNomenclatureRequest", Namespace="http://www.bars-open.ru/med/lis/", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public LisServiceClients.BarsNomenclature.Nomenclature[] sendNomenclatureRequest1;
        
        public sendNomenclatureRequest() {
        }
        
        public sendNomenclatureRequest(LisServiceClients.BarsNomenclature.Nomenclature[] sendNomenclatureRequest1) {
            this.sendNomenclatureRequest1 = sendNomenclatureRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendNomenclatureResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.bars-open.ru/med/lis/", Order=0)]
        public LisServiceClients.BarsNomenclature.sendNomenclatureResponse sendNomenclatureResponse;
        
        public sendNomenclatureResponse1() {
        }
        
        public sendNomenclatureResponse1(LisServiceClients.BarsNomenclature.sendNomenclatureResponse sendNomenclatureResponse) {
            this.sendNomenclatureResponse = sendNomenclatureResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LisBarsSendNomenclatureChannel : LisServiceClients.BarsNomenclature.LisBarsSendNomenclature, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LisBarsSendNomenclatureClient : System.ServiceModel.ClientBase<LisServiceClients.BarsNomenclature.LisBarsSendNomenclature>, LisServiceClients.BarsNomenclature.LisBarsSendNomenclature {
        
        public LisBarsSendNomenclatureClient() {
        }
        
        public LisBarsSendNomenclatureClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LisBarsSendNomenclatureClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LisBarsSendNomenclatureClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LisBarsSendNomenclatureClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LisServiceClients.BarsNomenclature.sendNomenclatureResponse1 LisServiceClients.BarsNomenclature.LisBarsSendNomenclature.sendNomenclature(LisServiceClients.BarsNomenclature.sendNomenclatureRequest request) {
            return base.Channel.sendNomenclature(request);
        }
        
        public LisServiceClients.BarsNomenclature.sendNomenclatureResponse sendNomenclature(LisServiceClients.BarsNomenclature.Nomenclature[] sendNomenclatureRequest1) {
            LisServiceClients.BarsNomenclature.sendNomenclatureRequest inValue = new LisServiceClients.BarsNomenclature.sendNomenclatureRequest();
            inValue.sendNomenclatureRequest1 = sendNomenclatureRequest1;
            LisServiceClients.BarsNomenclature.sendNomenclatureResponse1 retVal = ((LisServiceClients.BarsNomenclature.LisBarsSendNomenclature)(this)).sendNomenclature(inValue);
            return retVal.sendNomenclatureResponse;
        }
    }
}
