//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisServiceClients.EMIAS_Dictionaries {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://emias.gov.ru/servicetypes/1")]
    public partial class errorType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorCodeField;
        
        private string resultDescriptionField;
        
        private string exceptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string errorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("errorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string resultDescription {
            get {
                return this.resultDescriptionField;
            }
            set {
                this.resultDescriptionField = value;
                this.RaisePropertyChanged("resultDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string exception {
            get {
                return this.exceptionField;
            }
            set {
                this.exceptionField = value;
                this.RaisePropertyChanged("exception");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://emias.gov.ru/CUI/LaboratoryTypes/1")]
    public partial class li : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string codeField;
        
        private string omsCodeField;
        
        private string nameField;
        
        private string parentLiCodeField;
        
        private System.DateTime lastModifiedField;
        
        private bool urgencyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string omsCode {
            get {
                return this.omsCodeField;
            }
            set {
                this.omsCodeField = value;
                this.RaisePropertyChanged("omsCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string parentLiCode {
            get {
                return this.parentLiCodeField;
            }
            set {
                this.parentLiCodeField = value;
                this.RaisePropertyChanged("parentLiCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime lastModified {
            get {
                return this.lastModifiedField;
            }
            set {
                this.lastModifiedField = value;
                this.RaisePropertyChanged("lastModified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool urgency {
            get {
                return this.urgencyField;
            }
            set {
                this.urgencyField = value;
                this.RaisePropertyChanged("urgency");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://emias.gov.ru/CUI/LaboratoryService", ConfigurationName="EMIAS_Dictionaries.LaboratoryNsiServicePorts")]
    public interface LaboratoryNsiServicePorts {
        
        // CODEGEN: Generating message contract since the operation getLiList is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:#getLiList", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(LisServiceClients.EMIAS_Dictionaries.errorType), Action="urn:#getLiList", Name="fault", Namespace="http://emias.gov.ru/CUI/LaboratoryTypes/1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LisServiceClients.EMIAS_Dictionaries.getLiListResponse getLiList(LisServiceClients.EMIAS_Dictionaries.getLiListRequest request);
        
        // CODEGEN: Generating message contract since the operation getTestsList is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:#getTestsList", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(LisServiceClients.EMIAS_Dictionaries.errorType), Action="urn:#getTestsList", Name="fault", Namespace="http://emias.gov.ru/CUI/LaboratoryTypes/1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LisServiceClients.EMIAS_Dictionaries.getTestsListResponse getTestsList(LisServiceClients.EMIAS_Dictionaries.getTestsListRequest request);
        
        // CODEGEN: Generating message contract since the operation getLiTestsList is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:#getLiTestsList", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(LisServiceClients.EMIAS_Dictionaries.errorType), Action="urn:#getLiTestsList", Name="fault", Namespace="http://emias.gov.ru/CUI/LaboratoryTypes/1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LisServiceClients.EMIAS_Dictionaries.getLiTestsListResponse getLiTestsList(LisServiceClients.EMIAS_Dictionaries.getLiTestsListRequest request);
        
        // CODEGEN: Generating message contract since the operation getLocusList is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:#getLocusList", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(LisServiceClients.EMIAS_Dictionaries.errorType), Action="urn:#getLocusList", Name="fault", Namespace="http://emias.gov.ru/CUI/LaboratoryTypes/1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LisServiceClients.EMIAS_Dictionaries.getLocusListResponse getLocusList(LisServiceClients.EMIAS_Dictionaries.getLocusListRequest request);
        
        // CODEGEN: Generating message contract since the operation getTakeBiomatherialMethodsList is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:#getTakeBiomatherialMethodsList", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(LisServiceClients.EMIAS_Dictionaries.errorType), Action="urn:#getTakeBiomatherialMethodsList", Name="fault", Namespace="http://emias.gov.ru/CUI/LaboratoryTypes/1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LisServiceClients.EMIAS_Dictionaries.getTakeBiomatherialMethodsListResponse getTakeBiomatherialMethodsList(LisServiceClients.EMIAS_Dictionaries.getTakeBiomatherialMethodsListRequest request);
        
        // CODEGEN: Generating message contract since the operation getBiomatetialsList is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:#getBiomatetialsList", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(LisServiceClients.EMIAS_Dictionaries.errorType), Action="urn:#getBiomatetialsList", Name="fault", Namespace="http://emias.gov.ru/CUI/LaboratoryTypes/1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LisServiceClients.EMIAS_Dictionaries.getBiomatetialsListResponse getBiomatetialsList(LisServiceClients.EMIAS_Dictionaries.getBiomatetialsListRequest request);
        
        // CODEGEN: Generating message contract since the operation getVialsList is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:#getVialsList", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(LisServiceClients.EMIAS_Dictionaries.errorType), Action="urn:#getVialsList", Name="fault", Namespace="http://emias.gov.ru/CUI/LaboratoryTypes/1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LisServiceClients.EMIAS_Dictionaries.getVialsListResponse getVialsList(LisServiceClients.EMIAS_Dictionaries.getVialsListRequest request);
        
        // CODEGEN: Generating message contract since the operation getUnitsList is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:#getUnitsList", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(LisServiceClients.EMIAS_Dictionaries.errorType), Action="urn:#getUnitsList", Name="fault", Namespace="http://emias.gov.ru/CUI/LaboratoryTypes/1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LisServiceClients.EMIAS_Dictionaries.getUnitsListResponse getUnitsList(LisServiceClients.EMIAS_Dictionaries.getUnitsListRequest request);
        
        // CODEGEN: Generating message contract since the operation getAnthropometricDataList is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="urn:#getAnthropometricDataList", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(LisServiceClients.EMIAS_Dictionaries.errorType), Action="urn:#getAnthropometricDataList", Name="fault", Namespace="http://emias.gov.ru/CUI/LaboratoryTypes/1")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        LisServiceClients.EMIAS_Dictionaries.getAnthropometricDataListResponse getAnthropometricDataList(LisServiceClients.EMIAS_Dictionaries.getAnthropometricDataListRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://emias.gov.ru/CUI/LaboratoryTypes/1")]
    public partial class getLiRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime lastModifiedField;
        
        private bool lastModifiedFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime lastModified {
            get {
                return this.lastModifiedField;
            }
            set {
                this.lastModifiedField = value;
                this.RaisePropertyChanged("lastModified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastModifiedSpecified {
            get {
                return this.lastModifiedFieldSpecified;
            }
            set {
                this.lastModifiedFieldSpecified = value;
                this.RaisePropertyChanged("lastModifiedSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getLiListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://emias.gov.ru/CUI/LaboratoryTypes/1", Order=0)]
        public LisServiceClients.EMIAS_Dictionaries.getLiRequest getLiRequest;
        
        public getLiListRequest() {
        }
        
        public getLiListRequest(LisServiceClients.EMIAS_Dictionaries.getLiRequest getLiRequest) {
            this.getLiRequest = getLiRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getLiListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://emias.gov.ru/CUI/LaboratoryTypes/1", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public LisServiceClients.EMIAS_Dictionaries.li[] getLiResponse;
        
        public getLiListResponse() {
        }
        
        public getLiListResponse(LisServiceClients.EMIAS_Dictionaries.li[] getLiResponse) {
            this.getLiResponse = getLiResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://emias.gov.ru/CUI/LaboratoryTypes/1")]
    public partial class getTestsRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime lastModifiedField;
        
        private bool lastModifiedFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime lastModified {
            get {
                return this.lastModifiedField;
            }
            set {
                this.lastModifiedField = value;
                this.RaisePropertyChanged("lastModified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastModifiedSpecified {
            get {
                return this.lastModifiedFieldSpecified;
            }
            set {
                this.lastModifiedFieldSpecified = value;
                this.RaisePropertyChanged("lastModifiedSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://emias.gov.ru/CUI/LaboratoryTypes/1")]
    public partial class test : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string nameField;
        
        private string mnemonicCodeField;
        
        private bool isValidField;
        
        private System.DateTime lastModifiedField;
        
        private bool urgencyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string mnemonicCode {
            get {
                return this.mnemonicCodeField;
            }
            set {
                this.mnemonicCodeField = value;
                this.RaisePropertyChanged("mnemonicCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool isValid {
            get {
                return this.isValidField;
            }
            set {
                this.isValidField = value;
                this.RaisePropertyChanged("isValid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime lastModified {
            get {
                return this.lastModifiedField;
            }
            set {
                this.lastModifiedField = value;
                this.RaisePropertyChanged("lastModified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool urgency {
            get {
                return this.urgencyField;
            }
            set {
                this.urgencyField = value;
                this.RaisePropertyChanged("urgency");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTestsListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://emias.gov.ru/CUI/LaboratoryTypes/1", Order=0)]
        public LisServiceClients.EMIAS_Dictionaries.getTestsRequest getTestsRequest;
        
        public getTestsListRequest() {
        }
        
        public getTestsListRequest(LisServiceClients.EMIAS_Dictionaries.getTestsRequest getTestsRequest) {
            this.getTestsRequest = getTestsRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTestsListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://emias.gov.ru/CUI/LaboratoryTypes/1", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public LisServiceClients.EMIAS_Dictionaries.test[] getTestsResponse;
        
        public getTestsListResponse() {
        }
        
        public getTestsListResponse(LisServiceClients.EMIAS_Dictionaries.test[] getTestsResponse) {
            this.getTestsResponse = getTestsResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://emias.gov.ru/CUI/LaboratoryTypes/1")]
    public partial class getLiTestsRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime lastModifiedField;
        
        private bool lastModifiedFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime lastModified {
            get {
                return this.lastModifiedField;
            }
            set {
                this.lastModifiedField = value;
                this.RaisePropertyChanged("lastModified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastModifiedSpecified {
            get {
                return this.lastModifiedFieldSpecified;
            }
            set {
                this.lastModifiedFieldSpecified = value;
                this.RaisePropertyChanged("lastModifiedSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://emias.gov.ru/CUI/LaboratoryTypes/1")]
    public partial class liTest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string liIdField;
        
        private string testIdField;
        
        private bool isRequiredField;
        
        private System.DateTime lastModifiedField;
        
        private bool urgencyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string liId {
            get {
                return this.liIdField;
            }
            set {
                this.liIdField = value;
                this.RaisePropertyChanged("liId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string testId {
            get {
                return this.testIdField;
            }
            set {
                this.testIdField = value;
                this.RaisePropertyChanged("testId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool isRequired {
            get {
                return this.isRequiredField;
            }
            set {
                this.isRequiredField = value;
                this.RaisePropertyChanged("isRequired");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime lastModified {
            get {
                return this.lastModifiedField;
            }
            set {
                this.lastModifiedField = value;
                this.RaisePropertyChanged("lastModified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool urgency {
            get {
                return this.urgencyField;
            }
            set {
                this.urgencyField = value;
                this.RaisePropertyChanged("urgency");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getLiTestsListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://emias.gov.ru/CUI/LaboratoryTypes/1", Order=0)]
        public LisServiceClients.EMIAS_Dictionaries.getLiTestsRequest getLiTestsRequest;
        
        public getLiTestsListRequest() {
        }
        
        public getLiTestsListRequest(LisServiceClients.EMIAS_Dictionaries.getLiTestsRequest getLiTestsRequest) {
            this.getLiTestsRequest = getLiTestsRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getLiTestsListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://emias.gov.ru/CUI/LaboratoryTypes/1", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public LisServiceClients.EMIAS_Dictionaries.liTest[] getLiTestsResponse;
        
        public getLiTestsListResponse() {
        }
        
        public getLiTestsListResponse(LisServiceClients.EMIAS_Dictionaries.liTest[] getLiTestsResponse) {
            this.getLiTestsResponse = getLiTestsResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://emias.gov.ru/CUI/LaboratoryTypes/1")]
    public partial class getLocusRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime lastModifiedField;
        
        private bool lastModifiedFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime lastModified {
            get {
                return this.lastModifiedField;
            }
            set {
                this.lastModifiedField = value;
                this.RaisePropertyChanged("lastModified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastModifiedSpecified {
            get {
                return this.lastModifiedFieldSpecified;
            }
            set {
                this.lastModifiedFieldSpecified = value;
                this.RaisePropertyChanged("lastModifiedSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://emias.gov.ru/CUI/LaboratoryTypes/1")]
    public partial class locus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string nameField;
        
        private System.DateTime lastModifiedField;
        
        private bool urgencyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime lastModified {
            get {
                return this.lastModifiedField;
            }
            set {
                this.lastModifiedField = value;
                this.RaisePropertyChanged("lastModified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool urgency {
            get {
                return this.urgencyField;
            }
            set {
                this.urgencyField = value;
                this.RaisePropertyChanged("urgency");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getLocusListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://emias.gov.ru/CUI/LaboratoryTypes/1", Order=0)]
        public LisServiceClients.EMIAS_Dictionaries.getLocusRequest getLocusRequest;
        
        public getLocusListRequest() {
        }
        
        public getLocusListRequest(LisServiceClients.EMIAS_Dictionaries.getLocusRequest getLocusRequest) {
            this.getLocusRequest = getLocusRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getLocusListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://emias.gov.ru/CUI/LaboratoryTypes/1", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public LisServiceClients.EMIAS_Dictionaries.locus[] getLocusResponse;
        
        public getLocusListResponse() {
        }
        
        public getLocusListResponse(LisServiceClients.EMIAS_Dictionaries.locus[] getLocusResponse) {
            this.getLocusResponse = getLocusResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://emias.gov.ru/CUI/LaboratoryTypes/1")]
    public partial class getTakeBiomatherialMethodsRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime lastModifiedField;
        
        private bool lastModifiedFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime lastModified {
            get {
                return this.lastModifiedField;
            }
            set {
                this.lastModifiedField = value;
                this.RaisePropertyChanged("lastModified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastModifiedSpecified {
            get {
                return this.lastModifiedFieldSpecified;
            }
            set {
                this.lastModifiedFieldSpecified = value;
                this.RaisePropertyChanged("lastModifiedSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://emias.gov.ru/CUI/LaboratoryTypes/1")]
    public partial class takeBiomaterialMethod : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string textField;
        
        private System.DateTime lastModifiedField;
        
        private bool urgencyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("text");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime lastModified {
            get {
                return this.lastModifiedField;
            }
            set {
                this.lastModifiedField = value;
                this.RaisePropertyChanged("lastModified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool urgency {
            get {
                return this.urgencyField;
            }
            set {
                this.urgencyField = value;
                this.RaisePropertyChanged("urgency");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTakeBiomatherialMethodsListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://emias.gov.ru/CUI/LaboratoryTypes/1", Order=0)]
        public LisServiceClients.EMIAS_Dictionaries.getTakeBiomatherialMethodsRequest getTakeBiomatherialMethodsRequest;
        
        public getTakeBiomatherialMethodsListRequest() {
        }
        
        public getTakeBiomatherialMethodsListRequest(LisServiceClients.EMIAS_Dictionaries.getTakeBiomatherialMethodsRequest getTakeBiomatherialMethodsRequest) {
            this.getTakeBiomatherialMethodsRequest = getTakeBiomatherialMethodsRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTakeBiomatherialMethodsListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://emias.gov.ru/CUI/LaboratoryTypes/1", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("takeMethod", IsNullable=false)]
        public LisServiceClients.EMIAS_Dictionaries.takeBiomaterialMethod[] getTakeBiomatherialMethodsResponse;
        
        public getTakeBiomatherialMethodsListResponse() {
        }
        
        public getTakeBiomatherialMethodsListResponse(LisServiceClients.EMIAS_Dictionaries.takeBiomaterialMethod[] getTakeBiomatherialMethodsResponse) {
            this.getTakeBiomatherialMethodsResponse = getTakeBiomatherialMethodsResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://emias.gov.ru/CUI/LaboratoryTypes/1")]
    public partial class getBiomatetialsRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime lastModifiedField;
        
        private bool lastModifiedFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime lastModified {
            get {
                return this.lastModifiedField;
            }
            set {
                this.lastModifiedField = value;
                this.RaisePropertyChanged("lastModified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastModifiedSpecified {
            get {
                return this.lastModifiedFieldSpecified;
            }
            set {
                this.lastModifiedFieldSpecified = value;
                this.RaisePropertyChanged("lastModifiedSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://emias.gov.ru/CUI/LaboratoryTypes/1")]
    public partial class biomaterial : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string hl7CodeField;
        
        private string nameField;
        
        private System.DateTime lastModifiedField;
        
        private bool urgencyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string hl7Code {
            get {
                return this.hl7CodeField;
            }
            set {
                this.hl7CodeField = value;
                this.RaisePropertyChanged("hl7Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime lastModified {
            get {
                return this.lastModifiedField;
            }
            set {
                this.lastModifiedField = value;
                this.RaisePropertyChanged("lastModified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool urgency {
            get {
                return this.urgencyField;
            }
            set {
                this.urgencyField = value;
                this.RaisePropertyChanged("urgency");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBiomatetialsListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://emias.gov.ru/CUI/LaboratoryTypes/1", Order=0)]
        public LisServiceClients.EMIAS_Dictionaries.getBiomatetialsRequest getBiomatetialsRequest;
        
        public getBiomatetialsListRequest() {
        }
        
        public getBiomatetialsListRequest(LisServiceClients.EMIAS_Dictionaries.getBiomatetialsRequest getBiomatetialsRequest) {
            this.getBiomatetialsRequest = getBiomatetialsRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBiomatetialsListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://emias.gov.ru/CUI/LaboratoryTypes/1", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public LisServiceClients.EMIAS_Dictionaries.biomaterial[] getBiomatetialsResponse;
        
        public getBiomatetialsListResponse() {
        }
        
        public getBiomatetialsListResponse(LisServiceClients.EMIAS_Dictionaries.biomaterial[] getBiomatetialsResponse) {
            this.getBiomatetialsResponse = getBiomatetialsResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://emias.gov.ru/CUI/LaboratoryTypes/1")]
    public partial class getVialsRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime lastModifiedField;
        
        private bool lastModifiedFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime lastModified {
            get {
                return this.lastModifiedField;
            }
            set {
                this.lastModifiedField = value;
                this.RaisePropertyChanged("lastModified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastModifiedSpecified {
            get {
                return this.lastModifiedFieldSpecified;
            }
            set {
                this.lastModifiedFieldSpecified = value;
                this.RaisePropertyChanged("lastModifiedSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://emias.gov.ru/CUI/LaboratoryTypes/1")]
    public partial class vial : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string hl7CodeField;
        
        private string nameField;
        
        private System.DateTime lastModifiedField;
        
        private bool urgencyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string hl7Code {
            get {
                return this.hl7CodeField;
            }
            set {
                this.hl7CodeField = value;
                this.RaisePropertyChanged("hl7Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime lastModified {
            get {
                return this.lastModifiedField;
            }
            set {
                this.lastModifiedField = value;
                this.RaisePropertyChanged("lastModified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool urgency {
            get {
                return this.urgencyField;
            }
            set {
                this.urgencyField = value;
                this.RaisePropertyChanged("urgency");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getVialsListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://emias.gov.ru/CUI/LaboratoryTypes/1", Order=0)]
        public LisServiceClients.EMIAS_Dictionaries.getVialsRequest getVialsRequest;
        
        public getVialsListRequest() {
        }
        
        public getVialsListRequest(LisServiceClients.EMIAS_Dictionaries.getVialsRequest getVialsRequest) {
            this.getVialsRequest = getVialsRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getVialsListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://emias.gov.ru/CUI/LaboratoryTypes/1", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public LisServiceClients.EMIAS_Dictionaries.vial[] getVialsResponse;
        
        public getVialsListResponse() {
        }
        
        public getVialsListResponse(LisServiceClients.EMIAS_Dictionaries.vial[] getVialsResponse) {
            this.getVialsResponse = getVialsResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://emias.gov.ru/CUI/LaboratoryTypes/1")]
    public partial class getUnitsRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime lastModifiedField;
        
        private bool lastModifiedFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime lastModified {
            get {
                return this.lastModifiedField;
            }
            set {
                this.lastModifiedField = value;
                this.RaisePropertyChanged("lastModified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastModifiedSpecified {
            get {
                return this.lastModifiedFieldSpecified;
            }
            set {
                this.lastModifiedFieldSpecified = value;
                this.RaisePropertyChanged("lastModifiedSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://emias.gov.ru/CUI/LaboratoryTypes/1")]
    public partial class unit : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string hl7CodeField;
        
        private string nameField;
        
        private System.DateTime lastModifiedField;
        
        private bool urgencyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string hl7Code {
            get {
                return this.hl7CodeField;
            }
            set {
                this.hl7CodeField = value;
                this.RaisePropertyChanged("hl7Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime lastModified {
            get {
                return this.lastModifiedField;
            }
            set {
                this.lastModifiedField = value;
                this.RaisePropertyChanged("lastModified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool urgency {
            get {
                return this.urgencyField;
            }
            set {
                this.urgencyField = value;
                this.RaisePropertyChanged("urgency");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUnitsListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://emias.gov.ru/CUI/LaboratoryTypes/1", Order=0)]
        public LisServiceClients.EMIAS_Dictionaries.getUnitsRequest getUnitsRequest;
        
        public getUnitsListRequest() {
        }
        
        public getUnitsListRequest(LisServiceClients.EMIAS_Dictionaries.getUnitsRequest getUnitsRequest) {
            this.getUnitsRequest = getUnitsRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUnitsListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://emias.gov.ru/CUI/LaboratoryTypes/1", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public LisServiceClients.EMIAS_Dictionaries.unit[] getUnitsResponse;
        
        public getUnitsListResponse() {
        }
        
        public getUnitsListResponse(LisServiceClients.EMIAS_Dictionaries.unit[] getUnitsResponse) {
            this.getUnitsResponse = getUnitsResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://emias.gov.ru/CUI/LaboratoryTypes/1")]
    public partial class getAnthropometricDataRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.DateTime lastModifiedField;
        
        private bool lastModifiedFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime lastModified {
            get {
                return this.lastModifiedField;
            }
            set {
                this.lastModifiedField = value;
                this.RaisePropertyChanged("lastModified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lastModifiedSpecified {
            get {
                return this.lastModifiedFieldSpecified;
            }
            set {
                this.lastModifiedFieldSpecified = value;
                this.RaisePropertyChanged("lastModifiedSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://emias.gov.ru/CUI/LaboratoryTypes/1")]
    public partial class anthropometricData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codeField;
        
        private string nameField;
        
        private System.DateTime lastModifiedField;
        
        private bool urgencyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime lastModified {
            get {
                return this.lastModifiedField;
            }
            set {
                this.lastModifiedField = value;
                this.RaisePropertyChanged("lastModified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool urgency {
            get {
                return this.urgencyField;
            }
            set {
                this.urgencyField = value;
                this.RaisePropertyChanged("urgency");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAnthropometricDataListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://emias.gov.ru/CUI/LaboratoryTypes/1", Order=0)]
        public LisServiceClients.EMIAS_Dictionaries.getAnthropometricDataRequest getAnthropometricDataRequest;
        
        public getAnthropometricDataListRequest() {
        }
        
        public getAnthropometricDataListRequest(LisServiceClients.EMIAS_Dictionaries.getAnthropometricDataRequest getAnthropometricDataRequest) {
            this.getAnthropometricDataRequest = getAnthropometricDataRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAnthropometricDataListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://emias.gov.ru/CUI/LaboratoryTypes/1", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public LisServiceClients.EMIAS_Dictionaries.anthropometricData[] getAnthropometricDataResponse;
        
        public getAnthropometricDataListResponse() {
        }
        
        public getAnthropometricDataListResponse(LisServiceClients.EMIAS_Dictionaries.anthropometricData[] getAnthropometricDataResponse) {
            this.getAnthropometricDataResponse = getAnthropometricDataResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LaboratoryNsiServicePortsChannel : LisServiceClients.EMIAS_Dictionaries.LaboratoryNsiServicePorts, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LaboratoryNsiServicePortsClient : System.ServiceModel.ClientBase<LisServiceClients.EMIAS_Dictionaries.LaboratoryNsiServicePorts>, LisServiceClients.EMIAS_Dictionaries.LaboratoryNsiServicePorts {
        
        public LaboratoryNsiServicePortsClient() {
        }
        
        public LaboratoryNsiServicePortsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LaboratoryNsiServicePortsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LaboratoryNsiServicePortsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LaboratoryNsiServicePortsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LisServiceClients.EMIAS_Dictionaries.getLiListResponse LisServiceClients.EMIAS_Dictionaries.LaboratoryNsiServicePorts.getLiList(LisServiceClients.EMIAS_Dictionaries.getLiListRequest request) {
            return base.Channel.getLiList(request);
        }
        
        public LisServiceClients.EMIAS_Dictionaries.li[] getLiList(LisServiceClients.EMIAS_Dictionaries.getLiRequest getLiRequest) {
            LisServiceClients.EMIAS_Dictionaries.getLiListRequest inValue = new LisServiceClients.EMIAS_Dictionaries.getLiListRequest();
            inValue.getLiRequest = getLiRequest;
            LisServiceClients.EMIAS_Dictionaries.getLiListResponse retVal = ((LisServiceClients.EMIAS_Dictionaries.LaboratoryNsiServicePorts)(this)).getLiList(inValue);
            return retVal.getLiResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LisServiceClients.EMIAS_Dictionaries.getTestsListResponse LisServiceClients.EMIAS_Dictionaries.LaboratoryNsiServicePorts.getTestsList(LisServiceClients.EMIAS_Dictionaries.getTestsListRequest request) {
            return base.Channel.getTestsList(request);
        }
        
        public LisServiceClients.EMIAS_Dictionaries.test[] getTestsList(LisServiceClients.EMIAS_Dictionaries.getTestsRequest getTestsRequest) {
            LisServiceClients.EMIAS_Dictionaries.getTestsListRequest inValue = new LisServiceClients.EMIAS_Dictionaries.getTestsListRequest();
            inValue.getTestsRequest = getTestsRequest;
            LisServiceClients.EMIAS_Dictionaries.getTestsListResponse retVal = ((LisServiceClients.EMIAS_Dictionaries.LaboratoryNsiServicePorts)(this)).getTestsList(inValue);
            return retVal.getTestsResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LisServiceClients.EMIAS_Dictionaries.getLiTestsListResponse LisServiceClients.EMIAS_Dictionaries.LaboratoryNsiServicePorts.getLiTestsList(LisServiceClients.EMIAS_Dictionaries.getLiTestsListRequest request) {
            return base.Channel.getLiTestsList(request);
        }
        
        public LisServiceClients.EMIAS_Dictionaries.liTest[] getLiTestsList(LisServiceClients.EMIAS_Dictionaries.getLiTestsRequest getLiTestsRequest) {
            LisServiceClients.EMIAS_Dictionaries.getLiTestsListRequest inValue = new LisServiceClients.EMIAS_Dictionaries.getLiTestsListRequest();
            inValue.getLiTestsRequest = getLiTestsRequest;
            LisServiceClients.EMIAS_Dictionaries.getLiTestsListResponse retVal = ((LisServiceClients.EMIAS_Dictionaries.LaboratoryNsiServicePorts)(this)).getLiTestsList(inValue);
            return retVal.getLiTestsResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LisServiceClients.EMIAS_Dictionaries.getLocusListResponse LisServiceClients.EMIAS_Dictionaries.LaboratoryNsiServicePorts.getLocusList(LisServiceClients.EMIAS_Dictionaries.getLocusListRequest request) {
            return base.Channel.getLocusList(request);
        }
        
        public LisServiceClients.EMIAS_Dictionaries.locus[] getLocusList(LisServiceClients.EMIAS_Dictionaries.getLocusRequest getLocusRequest) {
            LisServiceClients.EMIAS_Dictionaries.getLocusListRequest inValue = new LisServiceClients.EMIAS_Dictionaries.getLocusListRequest();
            inValue.getLocusRequest = getLocusRequest;
            LisServiceClients.EMIAS_Dictionaries.getLocusListResponse retVal = ((LisServiceClients.EMIAS_Dictionaries.LaboratoryNsiServicePorts)(this)).getLocusList(inValue);
            return retVal.getLocusResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LisServiceClients.EMIAS_Dictionaries.getTakeBiomatherialMethodsListResponse LisServiceClients.EMIAS_Dictionaries.LaboratoryNsiServicePorts.getTakeBiomatherialMethodsList(LisServiceClients.EMIAS_Dictionaries.getTakeBiomatherialMethodsListRequest request) {
            return base.Channel.getTakeBiomatherialMethodsList(request);
        }
        
        public LisServiceClients.EMIAS_Dictionaries.takeBiomaterialMethod[] getTakeBiomatherialMethodsList(LisServiceClients.EMIAS_Dictionaries.getTakeBiomatherialMethodsRequest getTakeBiomatherialMethodsRequest) {
            LisServiceClients.EMIAS_Dictionaries.getTakeBiomatherialMethodsListRequest inValue = new LisServiceClients.EMIAS_Dictionaries.getTakeBiomatherialMethodsListRequest();
            inValue.getTakeBiomatherialMethodsRequest = getTakeBiomatherialMethodsRequest;
            LisServiceClients.EMIAS_Dictionaries.getTakeBiomatherialMethodsListResponse retVal = ((LisServiceClients.EMIAS_Dictionaries.LaboratoryNsiServicePorts)(this)).getTakeBiomatherialMethodsList(inValue);
            return retVal.getTakeBiomatherialMethodsResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LisServiceClients.EMIAS_Dictionaries.getBiomatetialsListResponse LisServiceClients.EMIAS_Dictionaries.LaboratoryNsiServicePorts.getBiomatetialsList(LisServiceClients.EMIAS_Dictionaries.getBiomatetialsListRequest request) {
            return base.Channel.getBiomatetialsList(request);
        }
        
        public LisServiceClients.EMIAS_Dictionaries.biomaterial[] getBiomatetialsList(LisServiceClients.EMIAS_Dictionaries.getBiomatetialsRequest getBiomatetialsRequest) {
            LisServiceClients.EMIAS_Dictionaries.getBiomatetialsListRequest inValue = new LisServiceClients.EMIAS_Dictionaries.getBiomatetialsListRequest();
            inValue.getBiomatetialsRequest = getBiomatetialsRequest;
            LisServiceClients.EMIAS_Dictionaries.getBiomatetialsListResponse retVal = ((LisServiceClients.EMIAS_Dictionaries.LaboratoryNsiServicePorts)(this)).getBiomatetialsList(inValue);
            return retVal.getBiomatetialsResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LisServiceClients.EMIAS_Dictionaries.getVialsListResponse LisServiceClients.EMIAS_Dictionaries.LaboratoryNsiServicePorts.getVialsList(LisServiceClients.EMIAS_Dictionaries.getVialsListRequest request) {
            return base.Channel.getVialsList(request);
        }
        
        public LisServiceClients.EMIAS_Dictionaries.vial[] getVialsList(LisServiceClients.EMIAS_Dictionaries.getVialsRequest getVialsRequest) {
            LisServiceClients.EMIAS_Dictionaries.getVialsListRequest inValue = new LisServiceClients.EMIAS_Dictionaries.getVialsListRequest();
            inValue.getVialsRequest = getVialsRequest;
            LisServiceClients.EMIAS_Dictionaries.getVialsListResponse retVal = ((LisServiceClients.EMIAS_Dictionaries.LaboratoryNsiServicePorts)(this)).getVialsList(inValue);
            return retVal.getVialsResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LisServiceClients.EMIAS_Dictionaries.getUnitsListResponse LisServiceClients.EMIAS_Dictionaries.LaboratoryNsiServicePorts.getUnitsList(LisServiceClients.EMIAS_Dictionaries.getUnitsListRequest request) {
            return base.Channel.getUnitsList(request);
        }
        
        public LisServiceClients.EMIAS_Dictionaries.unit[] getUnitsList(LisServiceClients.EMIAS_Dictionaries.getUnitsRequest getUnitsRequest) {
            LisServiceClients.EMIAS_Dictionaries.getUnitsListRequest inValue = new LisServiceClients.EMIAS_Dictionaries.getUnitsListRequest();
            inValue.getUnitsRequest = getUnitsRequest;
            LisServiceClients.EMIAS_Dictionaries.getUnitsListResponse retVal = ((LisServiceClients.EMIAS_Dictionaries.LaboratoryNsiServicePorts)(this)).getUnitsList(inValue);
            return retVal.getUnitsResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        LisServiceClients.EMIAS_Dictionaries.getAnthropometricDataListResponse LisServiceClients.EMIAS_Dictionaries.LaboratoryNsiServicePorts.getAnthropometricDataList(LisServiceClients.EMIAS_Dictionaries.getAnthropometricDataListRequest request) {
            return base.Channel.getAnthropometricDataList(request);
        }
        
        public LisServiceClients.EMIAS_Dictionaries.anthropometricData[] getAnthropometricDataList(LisServiceClients.EMIAS_Dictionaries.getAnthropometricDataRequest getAnthropometricDataRequest) {
            LisServiceClients.EMIAS_Dictionaries.getAnthropometricDataListRequest inValue = new LisServiceClients.EMIAS_Dictionaries.getAnthropometricDataListRequest();
            inValue.getAnthropometricDataRequest = getAnthropometricDataRequest;
            LisServiceClients.EMIAS_Dictionaries.getAnthropometricDataListResponse retVal = ((LisServiceClients.EMIAS_Dictionaries.LaboratoryNsiServicePorts)(this)).getAnthropometricDataList(inValue);
            return retVal.getAnthropometricDataResponse;
        }
    }
}
