//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MisExchangeEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExchangeContext : DbContext
    {
        public ExchangeContext()
            : base("name=ExchangeContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<RequestFilter> RequestFilterSet { get; set; }
        public DbSet<RequestFilterStatus> RequestFilterStatusSet { get; set; }
        public DbSet<Sample> SampleSet { get; set; }
        public DbSet<Target> TargetSet { get; set; }
        public DbSet<Request> RequestSet { get; set; }
        public DbSet<Patient> PatientSet { get; set; }
        public DbSet<PatientCard> PatientCardSet { get; set; }
        public DbSet<UserField> UserFieldSet { get; set; }
        public DbSet<RequestStatus> RequestStatusSet { get; set; }
        public DbSet<Result> ResultSet { get; set; }
        public DbSet<SampleResult> SampleResultSet { get; set; }
        public DbSet<Defect> DefectSet { get; set; }
        public DbSet<TargetResult> TargetResultSet { get; set; }
        public DbSet<MicroResult> MicroResultSet { get; set; }
        public DbSet<Work> WorkSet { get; set; }
        public DbSet<Norm> NormSet { get; set; }
        public DbSet<ResultStatus> ResultStatusSet { get; set; }
    }
}
