//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MisExchangeEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public Request()
        {
            this.UserFields = new HashSet<UserField>();
            this.Samples = new HashSet<Sample>();
        }
    
        public string RequestCode { get; set; }
        public string HospitalCode { get; set; }
        public string HospitalName { get; set; }
        public string DepartmentCode { get; set; }
        public string DepartmentName { get; set; }
        public string DoctorCode { get; set; }
        public string DoctorName { get; set; }
        public Nullable<System.DateTime> SamplingDate { get; set; }
        public Nullable<System.DateTime> SampleDeliveryDate { get; set; }
        public Nullable<int> PregnancyDuration { get; set; }
        public Nullable<int> CyclePeriod { get; set; }
        public Nullable<bool> ReadOnly { get; set; }
        public int Id { get; set; }
        public int PatientId { get; set; }
        public string PayCategoryCode { get; set; }
        public string Email { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual ICollection<UserField> UserFields { get; set; }
        public virtual ICollection<Sample> Samples { get; set; }
    }
}
