//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MisExchangeEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestFilter
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string PatientCodes { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<int> Sex { get; set; }
        public string RequestCodes { get; set; }
        public Nullable<System.DateTime> DateFrom { get; set; }
        public Nullable<System.DateTime> DateTill { get; set; }
        public string States { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> DefectState { get; set; }
        public string CustomStates { get; set; }
        public string Targets { get; set; }
        public string Departments { get; set; }
        public string Hospitals { get; set; }
        public string CustDepartments { get; set; }
        public string Doctors { get; set; }
        public Nullable<System.DateTime> EndDateFrom { get; set; }
        public Nullable<System.DateTime> EndDateTill { get; set; }
    }
}
