//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MisExchangeEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sample
    {
        public Sample()
        {
            this.Priority = 0;
            this.Targets = new HashSet<Target>();
        }
    
        public int Id { get; set; }
        public string Barcode { get; set; }
        public string BiomaterialCode { get; set; }
        public int Priority { get; set; }
        public int RequestId { get; set; }
    
        public virtual ICollection<Target> Targets { get; set; }
    }
}
