//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MisExchangeEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SampleResult
    {
        public SampleResult()
        {
            this.TargetResults = new HashSet<TargetResult>();
            this.MicroResults = new HashSet<MicroResult>();
            this.Defects = new HashSet<Defect>();
        }
    
        public int Id { get; set; }
        public string BiomaterialCode { get; set; }
        public string Barcode { get; set; }
        public string Comments { get; set; }
        public int ResultId { get; set; }
    
        public virtual Result Result { get; set; }
        public virtual ICollection<TargetResult> TargetResults { get; set; }
        public virtual ICollection<MicroResult> MicroResults { get; set; }
        public virtual ICollection<Defect> Defects { get; set; }
    }
}
