//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MisExchangeEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Target
    {
        public Target()
        {
            this.Priority = 0;
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public int Priority { get; set; }
        public Nullable<bool> ReadOnly { get; set; }
        public int SampleId { get; set; }
    
        public virtual Sample Sample { get; set; }
    }
}
