//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MisExchangeEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Work
    {
        public Work()
        {
            this.Defects = new HashSet<Defect>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public string UnitName { get; set; }
        public int State { get; set; }
        public string ApprovingDoctor { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<int> GroupRank { get; set; }
        public Nullable<int> RankInGroup { get; set; }
        public Nullable<int> TestRank { get; set; }
        public Nullable<int> Precision { get; set; }
        public string Comments { get; set; }
        public int Normality { get; set; }
        public Nullable<int> TargetResultId { get; set; }
        public Nullable<int> MicroResultId { get; set; }
    
        public virtual TargetResult TargetResult { get; set; }
        public virtual MicroResult MicroResult { get; set; }
        public virtual Norm Norm { get; set; }
        public virtual ICollection<Defect> Defects { get; set; }
    }
}
