//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LisServiceClients.LisServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestQueryData", Namespace="http://schemas.datacontract.org/2004/07/SportsReference.Facade.Lis")]
    [System.SerializableAttribute()]
    public partial class RequestQueryData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MaxResultsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MaxResults {
            get {
                return this.MaxResultsField;
            }
            set {
                if ((this.MaxResultsField.Equals(value) != true)) {
                    this.MaxResultsField = value;
                    this.RaisePropertyChanged("MaxResults");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestData", Namespace="http://schemas.datacontract.org/2004/07/SportsReference.Facade.Lis")]
    [System.SerializableAttribute()]
    public partial class RequestData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CyclePeriodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HospitalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HospitalNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LisServiceClients.LisServiceReference.PatientData PatientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> PregnancyDurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestCodeField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PurposeCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LisServiceClients.LisServiceReference.SampleData[] SamplesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LisServiceClients.LisServiceReference.UserFieldData[] UserFieldsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CyclePeriod {
            get {
                return this.CyclePeriodField;
            }
            set {
                if ((this.CyclePeriodField.Equals(value) != true)) {
                    this.CyclePeriodField = value;
                    this.RaisePropertyChanged("CyclePeriod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HospitalCode {
            get {
                return this.HospitalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.HospitalCodeField, value) != true)) {
                    this.HospitalCodeField = value;
                    this.RaisePropertyChanged("HospitalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HospitalName {
            get {
                return this.HospitalNameField;
            }
            set {
                if ((object.ReferenceEquals(this.HospitalNameField, value) != true)) {
                    this.HospitalNameField = value;
                    this.RaisePropertyChanged("HospitalName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LisServiceClients.LisServiceReference.PatientData Patient {
            get {
                return this.PatientField;
            }
            set {
                if ((object.ReferenceEquals(this.PatientField, value) != true)) {
                    this.PatientField = value;
                    this.RaisePropertyChanged("Patient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> PregnancyDuration {
            get {
                return this.PregnancyDurationField;
            }
            set {
                if ((this.PregnancyDurationField.Equals(value) != true)) {
                    this.PregnancyDurationField = value;
                    this.RaisePropertyChanged("PregnancyDuration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestCode {
            get {
                return this.RequestCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestCodeField, value) != true)) {
                    this.RequestCodeField = value;
                    this.RaisePropertyChanged("RequestCode");
                }
            }
        }


        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PurposeCode
        {
            get {
                return this.PurposeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PurposeCodeField, value) != true))
                {
                    this.PurposeCodeField = value;
                    this.RaisePropertyChanged("PurposeCode");
                }
            }
        }

        
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LisServiceClients.LisServiceReference.SampleData[] Samples {
            get {
                return this.SamplesField;
            }
            set {
                if ((object.ReferenceEquals(this.SamplesField, value) != true)) {
                    this.SamplesField = value;
                    this.RaisePropertyChanged("Samples");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LisServiceClients.LisServiceReference.UserFieldData[] UserFields {
            get {
                return this.UserFieldsField;
            }
            set {
                if ((object.ReferenceEquals(this.UserFieldsField, value) != true)) {
                    this.UserFieldsField = value;
                    this.RaisePropertyChanged("UserFields");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PatientData", Namespace="http://schemas.datacontract.org/2004/07/SportsReference.Facade.Lis")]
    [System.SerializableAttribute()]
    public partial class PatientData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BirthDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BirthMonthField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> BirthYearField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhotoUrlField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BloodGroupField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LisServiceClients.LisServiceReference.UserFieldData[] UserFieldsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BirthDay {
            get {
                return this.BirthDayField;
            }
            set {
                if ((this.BirthDayField.Equals(value) != true)) {
                    this.BirthDayField = value;
                    this.RaisePropertyChanged("BirthDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BirthMonth {
            get {
                return this.BirthMonthField;
            }
            set {
                if ((this.BirthMonthField.Equals(value) != true)) {
                    this.BirthMonthField = value;
                    this.RaisePropertyChanged("BirthMonth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> BirthYear {
            get {
                return this.BirthYearField;
            }
            set {
                if ((this.BirthYearField.Equals(value) != true)) {
                    this.BirthYearField = value;
                    this.RaisePropertyChanged("BirthYear");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNameField, value) != true)) {
                    this.MiddleNameField = value;
                    this.RaisePropertyChanged("MiddleName");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhotoUrl
        {
            get
            {
                return this.PhotoUrlField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PhotoUrlField, value) != true))
                {
                    this.PhotoUrlField = value;
                    this.RaisePropertyChanged("PhotoUrl");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BloodGroup
        {
            get
            {
                return this.BloodGroupField;
            }
            set
            {
                if ((object.ReferenceEquals(this.BloodGroupField, value) != true))
                {
                    this.BloodGroupField = value;
                    this.RaisePropertyChanged("BloodGroup");
                }
            }
        }

        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Sex {
            get {
                return this.SexField;
            }
            set {
                if ((this.SexField.Equals(value) != true)) {
                    this.SexField = value;
                    this.RaisePropertyChanged("Sex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LisServiceClients.LisServiceReference.UserFieldData[] UserFields {
            get {
                return this.UserFieldsField;
            }
            set {
                if ((object.ReferenceEquals(this.UserFieldsField, value) != true)) {
                    this.UserFieldsField = value;
                    this.RaisePropertyChanged("UserFields");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SampleData", Namespace="http://schemas.datacontract.org/2004/07/SportsReference.Facade.Lis")]
    [System.SerializableAttribute()]
    public partial class SampleData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BiomaterialCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LisServiceClients.LisServiceReference.TargetData[] TargetsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BiomaterialCode {
            get {
                return this.BiomaterialCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BiomaterialCodeField, value) != true)) {
                    this.BiomaterialCodeField = value;
                    this.RaisePropertyChanged("BiomaterialCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LisServiceClients.LisServiceReference.TargetData[] Targets {
            get {
                return this.TargetsField;
            }
            set {
                if ((object.ReferenceEquals(this.TargetsField, value) != true)) {
                    this.TargetsField = value;
                    this.RaisePropertyChanged("Targets");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserFieldData", Namespace="http://schemas.datacontract.org/2004/07/SportsReference.Facade.Lis")]
    [System.SerializableAttribute()]
    public partial class UserFieldData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TargetData", Namespace="http://schemas.datacontract.org/2004/07/SportsReference.Facade.Lis")]
    [System.SerializableAttribute()]
    public partial class TargetData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseData", Namespace="http://schemas.datacontract.org/2004/07/SportsReference.Facade.Lis")]
    [System.SerializableAttribute()]
    public partial class ResponseData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BiomaterialCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RequestCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TargetCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private LisServiceClients.LisServiceReference.TestData[] TestsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BiomaterialCode {
            get {
                return this.BiomaterialCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BiomaterialCodeField, value) != true)) {
                    this.BiomaterialCodeField = value;
                    this.RaisePropertyChanged("BiomaterialCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RequestCode {
            get {
                return this.RequestCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.RequestCodeField, value) != true)) {
                    this.RequestCodeField = value;
                    this.RaisePropertyChanged("RequestCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TargetCode {
            get {
                return this.TargetCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TargetCodeField, value) != true)) {
                    this.TargetCodeField = value;
                    this.RaisePropertyChanged("TargetCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public LisServiceClients.LisServiceReference.TestData[] Tests {
            get {
                return this.TestsField;
            }
            set {
                if ((object.ReferenceEquals(this.TestsField, value) != true)) {
                    this.TestsField = value;
                    this.RaisePropertyChanged("Tests");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TestData", Namespace="http://schemas.datacontract.org/2004/07/SportsReference.Facade.Lis")]
    [System.SerializableAttribute()]
    public partial class TestData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeviceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NormCommentField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NormalityField;       
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NormHighField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NormLowField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> TestStatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TestTypeCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UnitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Device {
            get {
                return this.DeviceField;
            }
            set {
                if ((object.ReferenceEquals(this.DeviceField, value) != true)) {
                    this.DeviceField = value;
                    this.RaisePropertyChanged("Device");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NormComment {
            get {
                return this.NormCommentField;
            }
            set {
                if ((object.ReferenceEquals(this.NormCommentField, value) != true)) {
                    this.NormCommentField = value;
                    this.RaisePropertyChanged("NormComment");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Normality
        {
            get
            {
                return this.NormalityField;
            }
            set
            {
                if ((object.ReferenceEquals(this.NormalityField, value) != true))
                {
                    this.NormalityField = value;
                    this.RaisePropertyChanged("Normality");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NormHigh {
            get {
                return this.NormHighField;
            }
            set {
                if ((object.ReferenceEquals(this.NormHighField, value) != true)) {
                    this.NormHighField = value;
                    this.RaisePropertyChanged("NormHigh");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NormLow {
            get {
                return this.NormLowField;
            }
            set {
                if ((object.ReferenceEquals(this.NormLowField, value) != true)) {
                    this.NormLowField = value;
                    this.RaisePropertyChanged("NormLow");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> TestStatus {
            get {
                return this.TestStatusField;
            }
            set {
                if ((this.TestStatusField.Equals(value) != true)) {
                    this.TestStatusField = value;
                    this.RaisePropertyChanged("TestStatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TestTypeCode {
            get {
                return this.TestTypeCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.TestTypeCodeField, value) != true)) {
                    this.TestTypeCodeField = value;
                    this.RaisePropertyChanged("TestTypeCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Unit {
            get {
                return this.UnitField;
            }
            set {
                if ((object.ReferenceEquals(this.UnitField, value) != true)) {
                    this.UnitField = value;
                    this.RaisePropertyChanged("Unit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.sportlogic.ru", ConfigurationName="LisServiceReference.ILisService")]
    public interface ILisService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.sportlogic.ru/ILisService/GetRequests", ReplyAction="http://schemas.sportlogic.ru/ILisService/GetRequestsResponse")]
        LisServiceClients.LisServiceReference.RequestData[] GetRequests(LisServiceClients.LisServiceReference.RequestQueryData query);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.sportlogic.ru/ILisService/GetRequestsConfirm", ReplyAction="http://schemas.sportlogic.ru/ILisService/GetRequestsConfirmResponse")]
        void GetRequestsConfirm(string[] requestCodes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.sportlogic.ru/ILisService/SetResponse", ReplyAction="http://schemas.sportlogic.ru/ILisService/SetResponseResponse")]
        bool SetResponse(LisServiceClients.LisServiceReference.ResponseData data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILisServiceChannel : LisServiceClients.LisServiceReference.ILisService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LisServiceClient : System.ServiceModel.ClientBase<LisServiceClients.LisServiceReference.ILisService>, LisServiceClients.LisServiceReference.ILisService {
        
        public LisServiceClient() {
        }
        
        public LisServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LisServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LisServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LisServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public LisServiceClients.LisServiceReference.RequestData[] GetRequests(LisServiceClients.LisServiceReference.RequestQueryData query) {
            return base.Channel.GetRequests(query);
        }
        
        public void GetRequestsConfirm(string[] requestCodes) {
            base.Channel.GetRequestsConfirm(requestCodes);
        }
        
        public bool SetResponse(LisServiceClients.LisServiceReference.ResponseData data) {
            return base.Channel.SetResponse(data);
        }
    }
}
