//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ru.novolabs.SuperCore.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ru.novolabs.SuperCore.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранение донаций в файл.
        /// </summary>
        internal static string Captions_ExportDonations {
            get {
                return ResourceManager.GetString("Captions_ExportDonations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выполнение донаций.
        /// </summary>
        internal static string Captions_ExportDonationsExec {
            get {
                return ResourceManager.GetString("Captions_ExportDonationsExec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перенос донаций на сервер ГСПК.
        /// </summary>
        internal static string Captions_ExportDonationsTransfer {
            get {
                return ResourceManager.GetString("Captions_ExportDonationsTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск контактов с ООИ.
        /// </summary>
        internal static string Captions_LoadingContacts {
            get {
                return ResourceManager.GetString("Captions_LoadingContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подключение, загрузка словарей ....
        /// </summary>
        internal static string Captions_LoadingDictionary {
            get {
                return ResourceManager.GetString("Captions_LoadingDictionary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поиск доноров ......
        /// </summary>
        internal static string Captions_LoadingDonors {
            get {
                return ResourceManager.GetString("Captions_LoadingDonors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Донор.
        /// </summary>
        internal static string Donor {
            get {
                return ResourceManager.GetString("Donor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фамилия.
        /// </summary>
        internal static string Donor_LastName {
            get {
                return ResourceManager.GetString("Donor_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Журнал доноров.
        /// </summary>
        internal static string DonorJournal {
            get {
                return ResourceManager.GetString("DonorJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на дней.
        /// </summary>
        internal static string DurationUnits_Days {
            get {
                return ResourceManager.GetString("DurationUnits_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на месяцев.
        /// </summary>
        internal static string DurationUnits_Monthes {
            get {
                return ResourceManager.GetString("DurationUnits_Monthes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на недель.
        /// </summary>
        internal static string DurationUnits_Weeks {
            get {
                return ResourceManager.GetString("DurationUnits_Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на лет.
        /// </summary>
        internal static string DurationUnits_Years {
            get {
                return ResourceManager.GetString("DurationUnits_Years", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Журнал ЕДЦ.
        /// </summary>
        internal static string EdcJournal {
            get {
                return ResourceManager.GetString("EdcJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не указан текст SQL-команды.
        /// </summary>
        internal static string EmptyCommandText {
            get {
                return ResourceManager.GetString("EmptyCommandText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не указана строка подключения к СУБД.
        /// </summary>
        internal static string EmptyConnectionString {
            get {
                return ResourceManager.GetString("EmptyConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не указан текст SQL-запроса.
        /// </summary>
        internal static string EmptyQueryText {
            get {
                return ResourceManager.GetString("EmptyQueryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        internal static string Erorrs_Error {
            get {
                return ResourceManager.GetString("Erorrs_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Справочник {0} не найден.
        /// </summary>
        internal static string Erors_DictionaryNotFound {
            get {
                return ResourceManager.GetString("Erors_DictionaryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Свойство {0} не найдено у справочника {1}..
        /// </summary>
        internal static string Errors_DictionaryPropertyNotFound {
            get {
                return ResourceManager.GetString("Errors_DictionaryPropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле класса {0} имеет тип {1}, контрол {2} принадлежит к классу {3}..
        /// </summary>
        internal static string Errors_ErrorReadingControl {
            get {
                return ResourceManager.GetString("Errors_ErrorReadingControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невозможно считать элемент формы..
        /// </summary>
        internal static string Errors_ErrorReadingControlCaption {
            get {
                return ResourceManager.GetString("Errors_ErrorReadingControlCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо заполнить поля: {0}.
        /// </summary>
        internal static string Errors_NeedToFillFields {
            get {
                return ResourceManager.GetString("Errors_NeedToFillFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Журнал донаций.
        /// </summary>
        internal static string ExpressDonationJournal {
            get {
                return ResourceManager.GetString("ExpressDonationJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Журнал донаций ГСПК.
        /// </summary>
        internal static string MasterExpressDonationJournal {
            get {
                return ResourceManager.GetString("MasterExpressDonationJournal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отвод на ОПК.
        /// </summary>
        internal static string Messages_DonationCancelResult {
            get {
                return ResourceManager.GetString("Messages_DonationCancelResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пустой пароль недопустим..
        /// </summary>
        internal static string Messages_EmptyPasswordImpossible {
            get {
                return ResourceManager.GetString("Messages_EmptyPasswordImpossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выплоненно {0} донаций.
        /// </summary>
        internal static string Messages_ExpressDonatiomExecuted {
            get {
                return ResourceManager.GetString("Messages_ExpressDonatiomExecuted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Экспортированно {0} донаций.
        /// </summary>
        internal static string Messages_ExpressDonatiomExported {
            get {
                return ResourceManager.GetString("Messages_ExpressDonatiomExported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранено {0} донаций.
        /// </summary>
        internal static string Messages_ExpressDonatiomSaved {
            get {
                return ResourceManager.GetString("Messages_ExpressDonatiomSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на У донора уже открыт визит..
        /// </summary>
        internal static string Messages_Has_Donation_Today {
            get {
                return ResourceManager.GetString("Messages_Has_Donation_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Некоректно введена дата рождения..
        /// </summary>
        internal static string Messages_IncorrectBirthDate {
            get {
                return ResourceManager.GetString("Messages_IncorrectBirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверно введена длительность отвода.
        /// </summary>
        internal static string Messages_IncorrectDenyDuration {
            get {
                return ResourceManager.GetString("Messages_IncorrectDenyDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адрес регистрации введен не полнотью, либо введен без использования классификатора адресов..
        /// </summary>
        internal static string Messages_IncorrectDocumentAdress {
            get {
                return ResourceManager.GetString("Messages_IncorrectDocumentAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверно указан тип или объем донации.
        /// </summary>
        internal static string Messages_IncorrectDonation {
            get {
                return ResourceManager.GetString("Messages_IncorrectDonation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Адрес проживания введен не полнотью, либо введен без использования классификатора адресов..
        /// </summary>
        internal static string Messages_IncorrectLivingAdress {
            get {
                return ResourceManager.GetString("Messages_IncorrectLivingAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверно указан номер.
        /// </summary>
        internal static string Messages_IncorrectNumber {
            get {
                return ResourceManager.GetString("Messages_IncorrectNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль не совпадает с подтверждением.
        /// </summary>
        internal static string Messages_IncorrectPasswordConfirmation {
            get {
                return ResourceManager.GetString("Messages_IncorrectPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введен неверный номер.
        /// </summary>
        internal static string Messages_Incorrst_Nr {
            get {
                return ResourceManager.GetString("Messages_Incorrst_Nr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите район города..
        /// </summary>
        internal static string Messages_KLADR_SelectDistrict {
            get {
                return ResourceManager.GetString("Messages_KLADR_SelectDistrict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите номер квартиры или поставьте символ &apos;-&apos;..
        /// </summary>
        internal static string Messages_KLADR_SelectFlat {
            get {
                return ResourceManager.GetString("Messages_KLADR_SelectFlat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите номер дома или поставьте символ &apos;-&apos;..
        /// </summary>
        internal static string Messages_KLADR_SelectHouse {
            get {
                return ResourceManager.GetString("Messages_KLADR_SelectHouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо выбрать регион..
        /// </summary>
        internal static string Messages_KLADR_SelectRegion {
            get {
                return ResourceManager.GetString("Messages_KLADR_SelectRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо выбрать улицу..
        /// </summary>
        internal static string Messages_KLADR_SelectStreet {
            get {
                return ResourceManager.GetString("Messages_KLADR_SelectStreet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо выбрать тип улицы..
        /// </summary>
        internal static string Messages_KLADR_SelectStreetType {
            get {
                return ResourceManager.GetString("Messages_KLADR_SelectStreetType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо выбрать населенный пункт..
        /// </summary>
        internal static string Messages_KLADR_SelectTown {
            get {
                return ResourceManager.GetString("Messages_KLADR_SelectTown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо выбрать тип населенного пункта..
        /// </summary>
        internal static string Messages_KLADR_SelectTownType {
            get {
                return ResourceManager.GetString("Messages_KLADR_SelectTownType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо корректно заполнить следующие поля:.
        /// </summary>
        internal static string Messages_NeedToFillFields {
            get {
                return ResourceManager.GetString("Messages_NeedToFillFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не найдено похожих доноров в базе данных..
        /// </summary>
        internal static string Messages_NoDonorFound {
            get {
                return ResourceManager.GetString("Messages_NoDonorFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не выбран результат донации  #{0}..
        /// </summary>
        internal static string Messages_Visit_No_Result {
            get {
                return ResourceManager.GetString("Messages_Visit_No_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не заполнены все необходимые поля визита {0}.
        /// </summary>
        internal static string Messages_Visit_Not_AllFields {
            get {
                return ResourceManager.GetString("Messages_Visit_Not_AllFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо ввести номер  донора или полные паспортные данные..
        /// </summary>
        internal static string Messages_VisitNotEnoughData {
            get {
                return ResourceManager.GetString("Messages_VisitNotEnoughData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Завершен.
        /// </summary>
        internal static string VisitState_Completed {
            get {
                return ResourceManager.GetString("VisitState_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В процессе.
        /// </summary>
        internal static string VisitState_InProgress {
            get {
                return ResourceManager.GetString("VisitState_InProgress", resourceCulture);
            }
        }
    }
}
